services:
  api:
    build:
      context: api
      dockerfile: ../Dockerfile_api
    ports:
     - "${API_PORT}:80"

  ocr_1:
    build:
      context: ocr_1
      dockerfile: ../Dockerfile_ocr_1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
     - "8007:80"
    volumes:
     - ${YOLO_PATH}:/weights
     - ${EASYOCR_PATH}:/.EasyOCR

